# Generated by Django 5.1.6 on 2025-02-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('doctor', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointemt',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.available_time'),
        ),
    ]
